<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
	  <PackageReference Include="Facet" Version="2.3.0" />
	  <PackageReference Include="Facet.Extensions" Version="2.3.0" />
	  <PackageReference Include="Facet.Extensions.EFCore" Version="2.3.0" />
    <ProjectReference Include="..\DataAccessLayer\DataAccessLayer.csproj" />
  </ItemGroup>

</Project>
